"""Project-wide constants."""

from __future__ import annotations

from datetime import timedelta

APP_NAME = "2xbrainz"
DEFAULT_SAMPLE_RATE_HZ = 16_000
DEFAULT_CHANNELS = 1
PCM_S16LE_SAMPLE_BYTES = 2
DEFAULT_FRAME_DURATION_MS = 20
PCM_S16LE_BYTEORDER = "little"
VAD_SPEECH_START_PROBABILITY = 0.5
VAD_SPEECH_STOP_PROBABILITY = 0.35
VAD_SPEECH_START_WINDOW_COUNT = 2
VAD_SILENCE_WINDOW_COUNT = 25
VAD_PRE_ROLL_FRAME_COUNT = 10
VAD_MAX_SEGMENT_SECONDS = 60
PCM_S16LE_BYTES_PER_SECOND = (
    DEFAULT_SAMPLE_RATE_HZ * DEFAULT_CHANNELS * PCM_S16LE_SAMPLE_BYTES
)
VAD_MAX_SEGMENT_AUDIO_BYTES = PCM_S16LE_BYTES_PER_SECOND * VAD_MAX_SEGMENT_SECONDS
DEFAULT_FRAME_BYTES = (
    DEFAULT_SAMPLE_RATE_HZ
    * DEFAULT_FRAME_DURATION_MS
    // 1_000
    * PCM_S16LE_SAMPLE_BYTES
    * DEFAULT_CHANNELS
)
MAX_CAPTURE_FRAME_GAP_SECONDS = DEFAULT_FRAME_DURATION_MS * 2 / 1_000
MAX_INTER_STREAM_DRIFT_PENDING_FRAMES = 256
MAX_AUDIO_FIXTURE_BYTES = 5_000_000
MAX_AUDIO_FIXTURE_DURATION_SECONDS = 300
MAX_REFERENCE_TEXT_BYTES = 65_536
MAX_ASR_EVALUATION_WORDS = 2_048
MAX_EVENT_BYTES = 65_536
MAX_REPLAY_LINE_BYTES = 65_536
MAX_PROVIDER_RESPONSE_BYTES = 1_000_000
MAX_AIGATE_MODEL_ID_CHARACTERS = 200
MAX_PROVIDER_SELECTION_CONFIG_BYTES = 4_096
DEFAULT_HTTP_TIMEOUT = timedelta(seconds=15)
DEFAULT_PROVIDER_GENERATION_DEADLINE = timedelta(seconds=60)
DEFAULT_WS_PING_INTERVAL_SECONDS = 20
DEFAULT_WS_CLOSE_TIMEOUT_SECONDS = 10
DEFAULT_LOG_ROTATION_BYTES = 5_000_000
DEFAULT_LOG_BACKUP_COUNT = 3
MAX_DRAFT_RESULT_BACKLOG = 1
MAX_INSIGHT_RESULT_BACKLOG = 4
MAX_DRAFT_TEXT_CHARACTERS = 1_000
MAX_REPLY_DRAFT_TOKENS = 1_024
MAX_COMMENTARY_TEXT_CHARACTERS = 1_000
MAX_COMMENTARY_TOKENS = 1_024
MAX_SUMMARY_TEXT_CHARACTERS = 2_000
MAX_SUMMARY_TOKENS = 1_024
MAX_RECENT_TRANSCRIPT_LINES = 64
MAX_SESSION_BRIEF_CHARACTERS = 4_000
MAX_AIGATE_TOOL_CALLS = 3
MAX_AIGATE_TOOL_ROUNDS = 2
MAX_EMPTY_COMPLETION_RETRIES = 1
MAX_CALCULATION_EXPRESSION_CHARACTERS = 256
MAX_CALCULATION_AST_NODES = 64
MAX_CALCULATION_AST_DEPTH = 12
MAX_CALCULATION_ABSOLUTE_CONSTANT = 1_000_000_000_000
MAX_CALCULATION_POWER_BASE = 1_000_000
MAX_CALCULATION_POWER_EXPONENT = 12
MAX_WEB_SEARCH_QUERY_CHARACTERS = 256
MAX_WEB_SEARCH_RESULT_TITLE_CHARACTERS = 240
MAX_WEB_SEARCH_RESULT_URL_CHARACTERS = 2_048
MAX_WEB_SEARCH_RESULT_SNIPPET_CHARACTERS = 1_000
WEB_SEARCH_RESULTS_PER_CALL = 5
MAX_AIGATE_TOOL_RESULT_CHARACTERS = 6_000
MAX_RESEARCH_DISCOVERED_LINKS = 8
MAX_RESEARCH_LINK_LABEL_CHARACTERS = 160
MAX_PROVIDER_ACTIVITY_TEXT_CHARACTERS = 12_000
MAX_PROVIDER_ERROR_MESSAGE_CHARACTERS = 240
RESEARCH_RESULT_MATCH_PERCENT = 60
MAX_RESEARCH_URL_CHARACTERS = 2_048
TALKIES_STREAM_PATH = "/v1/audio/transcriptions/stream"
TALKIES_BATCH_PATH = "/v1/audio/transcriptions"
TALKIES_MODELS_PATH = "/v1/models"
# Both are relative to TWOXBRAINZ_AIGATE_URL, which carries AIGate's API prefix.
AIGATE_CHAT_COMPLETIONS_PATH = "/chat/completions"
AIGATE_MODELS_PATH = "/models"
AIGATE_MCP_PATH = "/mcp/"
ENV_PREFIX = "TWOXBRAINZ_"
ENV_TALKIES_MODEL = f"{ENV_PREFIX}TALKIES_MODEL"
ENV_AIGATE_URL = f"{ENV_PREFIX}AIGATE_URL"
ENV_AIGATE_REPLY_MODEL = f"{ENV_PREFIX}AIGATE_REPLY_MODEL"
ENV_AIGATE_COACH_MODEL = f"{ENV_PREFIX}AIGATE_COACH_MODEL"
ENV_AIGATE_SUMMARY_MODEL = f"{ENV_PREFIX}AIGATE_SUMMARY_MODEL"
ENV_AIGATE_REPLY_REASONING_EFFORT = f"{ENV_PREFIX}AIGATE_REPLY_REASONING_EFFORT"
ENV_AIGATE_COACH_REASONING_EFFORT = f"{ENV_PREFIX}AIGATE_COACH_REASONING_EFFORT"
ENV_AIGATE_SUMMARY_REASONING_EFFORT = f"{ENV_PREFIX}AIGATE_SUMMARY_REASONING_EFFORT"
ENV_AIGATE_TOKEN = f"{ENV_PREFIX}AIGATE_TOKEN"
ENV_SESSION_BRIEF = f"{ENV_PREFIX}SESSION_BRIEF"
ENV_WEB_RESEARCH_ENABLED = f"{ENV_PREFIX}WEB_RESEARCH_ENABLED"
ENV_LOG_LEVEL = f"{ENV_PREFIX}LOG_LEVEL"
ENV_LOG_DIRECTORY = f"{ENV_PREFIX}LOG_DIRECTORY"
ENV_LOG_FILE = f"{ENV_PREFIX}LOG_FILE"
ENV_AUDIO_CONFIG_FILE = f"{ENV_PREFIX}AUDIO_CONFIG_FILE"
DEFAULT_TALKIES_MODEL = "nemotron-3.5-asr-0.6b"
DEFAULT_AIGATE_URL = "http://localhost:4000/v1"
DEFAULT_AIGATE_REASONING_EFFORT = "none"
AIGATE_REASONING_EFFORTS = frozenset({"none", "minimal", "low", "medium", "high"})
WEB_RESEARCH_ENABLED_VALUE = "true"
DEFAULT_WEB_RESEARCH_ENABLED = False
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_FILE = "/tmp/2xbrainz.log"
DEFAULT_LOG_FILENAME = "2xbrainz.log"
DEFAULT_AUDIO_CONFIG_FILE = "/home/app/.config/2xbrainz/audio-selection.json"
DEFAULT_PROVIDER_CONFIG_FILENAME = "provider-selection.json"
PROVIDER_SELECTION_CONFIG_SCHEMA_VERSION = 2
WEB_CONSOLE_HOST = "127.0.0.1"
DEFAULT_WEB_CONSOLE_PORT = 7860
MIN_WEB_CONSOLE_PORT = 1024
MAX_WEB_CONSOLE_PORT = 65_535
MAX_AUDIO_SELECTION_CONFIG_BYTES = 4_096
AUDIO_SELECTION_CONFIG_SCHEMA_VERSION = 1
JSON_CONTENT_TYPE = "application/json"
JSON_RECORD_SCHEMA_VERSION = 1
BEARER_PREFIX = "Bearer "
HEADER_AUTHORIZATION = "Authorization"
HEADER_CONTENT_TYPE = "Content-Type"
HEADER_ACCEPT = "Accept"
HEADER_USER_AGENT = "User-Agent"
HEADER_REQUEST_ID = "X-Request-Id"
PIPEWIRE_RECORD_COMMAND = "pw-record"
PIPEWIRE_OUTPUT_TARGET = "-"
PIPEWIRE_FORMAT_S16 = "s16"
PIPEWIRE_OPTION_TARGET = "--target"
PIPEWIRE_OPTION_RATE = "--rate"
PIPEWIRE_OPTION_CHANNELS = "--channels"
PIPEWIRE_OPTION_FORMAT = "--format"
PIPEWIRE_OPTION_LATENCY = "--latency"
PIPEWIRE_OPTION_PROPERTIES = "--properties"
PIPEWIRE_LATENCY = "20ms"
PIPEWIRE_SINK_CAPTURE_PROPERTIES = (
    "{ stream.capture.sink = true node.dont-fallback = true }"
)
LOG_REDACTION_VALUE = "[REDACTED]"
MCP_ACCEPT_HEADER_VALUE = "application/json, text/event-stream"
