"""Project-wide constants."""

from __future__ import annotations

from datetime import timedelta

APP_NAME = "2xbrainz"
DEFAULT_SAMPLE_RATE_HZ = 16_000
DEFAULT_CHANNELS = 1
PCM_S16LE_SAMPLE_BYTES = 2
DEFAULT_FRAME_DURATION_MS = 20
PCM_S16LE_BYTEORDER = "little"
SPEECH_ACTIVITY_SAMPLE_THRESHOLD = 256
SPEECH_TURN_SILENCE_FRAME_COUNT = 40
PCM_S16LE_BYTES_PER_SECOND = (
    DEFAULT_SAMPLE_RATE_HZ * DEFAULT_CHANNELS * PCM_S16LE_SAMPLE_BYTES
)
DEFAULT_FRAME_BYTES = (
    DEFAULT_SAMPLE_RATE_HZ
    * DEFAULT_FRAME_DURATION_MS
    // 1_000
    * PCM_S16LE_SAMPLE_BYTES
    * DEFAULT_CHANNELS
)
MAX_CAPTURE_FRAME_GAP_SECONDS = DEFAULT_FRAME_DURATION_MS * 2 / 1_000
MAX_INTER_STREAM_DRIFT_PENDING_FRAMES = 256
MAX_AUDIO_FIXTURE_BYTES = 5_000_000
MAX_AUDIO_FIXTURE_DURATION_SECONDS = 300
MAX_REFERENCE_TEXT_BYTES = 65_536
MAX_ASR_EVALUATION_WORDS = 2_048
MAX_EVENT_BYTES = 65_536
MAX_REPLAY_LINE_BYTES = 65_536
MAX_PROVIDER_RESPONSE_BYTES = 1_000_000
DEFAULT_HTTP_TIMEOUT = timedelta(seconds=15)
DEFAULT_PROVIDER_GENERATION_DEADLINE = DEFAULT_HTTP_TIMEOUT
DEFAULT_WS_PING_INTERVAL_SECONDS = 20
DEFAULT_WS_CLOSE_TIMEOUT_SECONDS = 10
DEFAULT_LOG_ROTATION_BYTES = 5_000_000
DEFAULT_LOG_BACKUP_COUNT = 3
MAX_DRAFT_RESULT_BACKLOG = 1
MAX_DRAFT_OUTCOME_BACKLOG = 64
MAX_INSIGHT_RESULT_BACKLOG = 4
MAX_DRAFT_TEXT_CHARACTERS = 1_000
MAX_REPLY_DRAFT_TOKENS = 512
MAX_COMMENTARY_TEXT_CHARACTERS = 1_000
MAX_COMMENTARY_TOKENS = 128
MAX_SUMMARY_TEXT_CHARACTERS = 2_000
MAX_SUMMARY_TOKENS = 256
MAX_RECENT_TRANSCRIPT_LINES = 64
TALKIES_STREAM_PATH = "/v1/audio/transcriptions/stream"
TALKIES_BATCH_PATH = "/v1/audio/transcriptions"
TALKIES_MODELS_PATH = "/v1/models"
# Both are relative to TWOXBRAINZ_AIGATE_URL, which carries the API prefix (the
# usual OpenAI-client convention). Keep them consistent: a "/v1" on one and not
# the other means no single base URL can satisfy both, which is invisible
# against AIGate -- its nginx forwards verbatim to LiteLLM, and LiteLLM answers
# on the prefixed and unprefixed form alike -- but breaks on OpenAI and Groq,
# which serve only /v1.
AIGATE_CHAT_COMPLETIONS_PATH = "/chat/completions"
AIGATE_MODELS_PATH = "/models"
ENV_PREFIX = "TWOXBRAINZ_"
ENV_TALKIES_WS_URL = f"{ENV_PREFIX}TALKIES_WS_URL"
ENV_TALKIES_MODEL = f"{ENV_PREFIX}TALKIES_MODEL"
ENV_TALKIES_TOKEN = f"{ENV_PREFIX}TALKIES_TOKEN"
ENV_AIGATE_URL = f"{ENV_PREFIX}AIGATE_URL"
ENV_AIGATE_MODEL = f"{ENV_PREFIX}AIGATE_MODEL"
ENV_AIGATE_TOKEN = f"{ENV_PREFIX}AIGATE_TOKEN"
ENV_AIGATE_MODE = f"{ENV_PREFIX}AIGATE_MODE"
ENV_REMOTE_TEXT_ENABLED = f"{ENV_PREFIX}REMOTE_TEXT_ENABLED"
ENV_LOG_LEVEL = f"{ENV_PREFIX}LOG_LEVEL"
ENV_LOG_FILE = f"{ENV_PREFIX}LOG_FILE"
# Defaults describe the AIGate deployment reached over the host network, which
# is what `make live` uses: AIGate publishes one port, Talkies has no host port
# binding of its own and is served through the gateway at /talkies/. Joining a
# specific Docker network instead means swapping localhost for the service name.
# A standalone Talkies box is still supported -- point TALKIES_WS_URL at it
# directly and give it its own token, since it no longer shares the gateway's
# authority.
DEFAULT_TALKIES_WS_URL = f"ws://localhost:4000/talkies{TALKIES_STREAM_PATH}"
DEFAULT_TALKIES_MODEL = "nemotron-3.5-asr-0.6b"
DEFAULT_AIGATE_URL = "http://localhost:4000/v1"
DEFAULT_AIGATE_MODE = "local"
REMOTE_TEXT_ENABLED_VALUE = "true"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_FILE = "/tmp/2xbrainz.log"
JSON_CONTENT_TYPE = "application/json"
JSON_RECORD_SCHEMA_VERSION = 1
BEARER_PREFIX = "Bearer "
HEADER_AUTHORIZATION = "Authorization"
HEADER_CONTENT_TYPE = "Content-Type"
HEADER_REQUEST_ID = "X-Request-Id"
PIPEWIRE_RECORD_COMMAND = "pw-record"
PIPEWIRE_OUTPUT_TARGET = "-"
PIPEWIRE_FORMAT_S16 = "s16"
PIPEWIRE_OPTION_TARGET = "--target"
PIPEWIRE_OPTION_RATE = "--rate"
PIPEWIRE_OPTION_CHANNELS = "--channels"
PIPEWIRE_OPTION_FORMAT = "--format"
PIPEWIRE_OPTION_LATENCY = "--latency"
PIPEWIRE_LATENCY = "20ms"
LOG_REDACTION_VALUE = "[REDACTED]"
